name: evidence
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - flake8
  - jupyterlab>=3.0
  - matplotlib
  - mypy
  - omegaconf
  - pandas
  - pip
  - python=3.9
  - pyyaml
  - pip:
      - tensorflow
