name: cifar10
data:
  batch_size: 1000

model:
  hidden_layers: 5
  hidden_units: 100
  input_shape: (32, 32, 3)
  output_units: 10

fit:
  epochs: 200

experiments:
  no_regularization:
    model:
      kernel_regularizer: None
  l1:
    model:
      kernel_regularizer: l1
  l2:
    model:
      kernel_regularizer: l2
  l1_l2:
    model:
      kernel_regularizer: l1_l2
  dropout:
    model:
      dropout: True
  evidence_regularizer:
    model:
      evidence_regularizer_kwargs:
        threshold: 100
        cutoff: 0
