name: cifar10
data:
  batch_size: 1000

model:
  hidden_layers: 10
  hidden_units: 100
  input_shape:
    - 32
    - 32
    - 3
  output_units: 10

fit:
  epochs: 100

experiments:
  no_regularization:
    model:
      kernel_regularizer: Null
  l1:
    model:
      kernel_regularizer: l1
  l2:
    model:
      kernel_regularizer: l2
  dropout:
    model:
      dropout: True
  evidence_regularizer:
    model:
      evidence_regularizer_kwargs:
        threshold: 10
        cutoff: 0
